import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Career Dashboard</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          Career Dashboard
        </h1>

        <p className={styles.description}>
          This is an example of a <code>Progressive Web App</code> Career Dashboard
        </p>

        <div className={styles.grid}>
          <a href="#" className={styles.card}>
            <h2>Skills</h2>
            <p>Check out the skills you have earned along the way.</p>
          </a>

          <a href="#" className={styles.card}>
            <h2>Journey</h2>
            <p>Plan out your career journey.</p>
          </a>

          <a href="#" className={styles.card}>
            <h2>Contact &rarr;</h2>
            <p>Get in touch with a Career Advisor.</p>
          </a>

          <a href="#" className={styles.card}>
            <h2>Ammon</h2>
            <p>Ammon is awesome :)</p>
          </a>
        </div>
      </main>

      <footer className={styles.footer}>
        Powered by <code>next.js</code> and <code>next-pwa</code>
      </footer>
    </div>
  )
}
